version: "3.4"

services:
  hub:
    image: ${ECR_ENDPOINT}@${DIGEST}
    deploy:
      labels:
        cardstack_travis_build: ${GITHUB_BUILD_ID}
      replicas: 1
      update_config:
        order: start-first
        failure_action: rollback
    ports:
      - "3000:3000"
    environment:
      - PGHOST
      - PGPORT
      - PGUSER
      - PGPASSWORD
      - LOG_LEVELS
      - TARGET_ENV
      - TARGET_NAME
      - TEST
      - NODE_OPTIONS
      - HUB_ENVIRONMENT
      - HUB_URL
      - META_REALM_URL
      - DEFAULT_REALM_URL
      - CARDSTACK_SESSIONS_KEY

networks:
  default:
    ipam:
      config:
        - subnet: 172.28.0.0/16
