---
language: node_js
node_js:
  - "8"
  - "10"

sudo: required
services:
 - docker

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - libstdc++-4.9-dev

env:
  global:
    - ELASTICSEARCH=http://127.0.0.1:9200
    - PGHOST=localhost
    - PGPORT=5444
    - PGUSER=postgres

cache:
  directories:
    - node_modules

before_install:
  - docker run -d --rm -p 9200:9200 --name elasticsearch cardstack/elasticsearch:dev
  - docker run -d --rm -p 5444:5432 --name postgres cardstack/pg-test
  - docker run -d --rm -p 9022:22 --name git-ssh cardstack/git-test;
  - ssh-keyscan -p 9022 -t rsa,ecdsa-sha2-nistp256 localhost >> $HOME/.ssh/known_hosts
  - chmod 600 packages/git/node-tests/git-ssh-server/cardstack-test-key
  - export PATH=$HOME/.yarn/bin:$PATH

install:
  - yarn install
  - travis_wait ./node_modules/.bin/lerna bootstrap

before_script:
 - yarn run blockchain &
 - wget -q --waitretry=1 --retry-connrefused -T 1 -O - http://127.0.0.1:9200
 - node packages/postgresql/node-tests/pg-server/wait-for-db.js

script:
  - yarn test
