name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - uses: volta-cli/action@v1
    - name: Set up build cache (yarn)
      uses: actions/cache@v2
      with:
        path: ~/.cache/yarn
        key: ${{ runner.os }}-yarn-${{ hashFiles('/**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - run: yarn install
    # - name: Setup tmate session
    #   uses: mxschmitt/action-tmate@v3
    #   timeout-minutes: 90
    - run: yarn lint
    - run: yarn test

  deploy-web-client-staging:
    name: Deploy a preview to S3
    runs-on: ubuntu-latest
    # github.event.pull_request.head.repo.full_name == github.repository: true if pr is from the original repo, false if it's from a fork
    # github.head_ref: the branch that the pull request is from. only appears on pull_request events
    if: github.ref == 'refs/heads/main'
    needs: [test]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - uses: volta-cli/action@v1
    - name: Set up build cache (yarn)
      uses: actions/cache@v2
      with:
        path: ~/.cache/yarn
        key: ${{ runner.os }}-yarn-${{ hashFiles('/**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - run: yarn install
    - name: Run ember-cli-deploy
      run: yarn run ember deploy staging
