name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Build & Lint
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - uses: volta-cli/action@v1
    - name: Set up yarn cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/yarn
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - run: yarn global add lerna
    - run: lerna bootstrap
    - run: yarn lint

  hub-test:
    name: Hub node tests
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - uses: volta-cli/action@v1
    - name: Set up yarn cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/yarn
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - run: yarn global add lerna
    - run: lerna bootstrap
    # - name: Setup tmate session
    #   uses: mxschmitt/action-tmate@v3
    #   timeout-minutes: 90
    - run: yarn test:hub

  web-client-test:
    name: web-client Ember tests
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - uses: volta-cli/action@v1
    - name: Set up yarn cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/yarn
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - run: yarn global add lerna
    - run: lerna bootstrap
    # - name: Setup tmate session
    #   uses: mxschmitt/action-tmate@v3
    #   timeout-minutes: 90
    - run: yarn test:web-client

  deploy-web-client-staging:
    name: Deploy web-client to S3 staging bucket
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    needs: [web-client-test, hub-test]
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
    - uses: volta-cli/action@v1
    - name: Set up yarn cache
      uses: actions/cache@v2
      with:
        path: ~/.cache/yarn
        key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
        restore-keys: |
          ${{ runner.os }}-yarn-
    - run: yarn global add lerna
    - run: lerna bootstrap
    - name: Run ember-cli-deploy
      run: yarn deploy:web-client:staging
      env:
        EMBER_DEPLOY_AWS_ACCESS_KEY: ${{ secrets.STAGING_EMBER_DEPLOY_AWS_ACCESS_KEY }}
        EMBER_DEPLOY_AWS_ACCESS_SECRET: ${{ secrets.STAGING_EMBER_DEPLOY_AWS_ACCESS_SECRET }}
